version: '3.8'

services:
  # Application Service
  app:
    build: .
    container_name: imticket-app
    ports:
      - "10080:10080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_DOCKER}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      SPRING_SERVLET_MULTIPART_LOCATION: /app/uploads
      TICKET_UPLOAD_PATH: /app/uploads
    # Database Config
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - imticket-network
    volumes:
      - ./uploads:/app/uploads # Persist uploads locally

  # Redis Service
  redis:
    image: redis:alpine
    container_name: imticket-redis
    ports:
      - "6379:6379"
    networks:
      - imticket-network

  # MySQL Service (Optional: If you want to run DB in Docker)
  mysql:
    image: mysql:8.0
    container_name: imticket-mysql
    ports:
      - "10047:3306" # Expose on 10047 to avoid conflict with local DB on 10046/3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql # Persist data
    networks:
      - imticket-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Prometheus Service
  prometheus:
    image: prom/prometheus
    container_name: imticket-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - imticket-network

  # Grafana Service
  grafana:
    image: grafana/grafana
    container_name: imticket-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    networks:
      - imticket-network
    depends_on:
      - prometheus

networks:
  imticket-network:
    driver: bridge

volumes:
  mysql-data:
