global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'imticket-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['imticket-app:10080'] # Use container name and internal port
